DATA_ROOT: "C:/Users/thisi/Desktop/ErfanMhp/University4032/CV/project/"
RUNS_DIR: "./runs"
OUTPUTS_DIR: "./outputs"

IMG_SIZE: 512
BATCH_SIZE: 1
NUM_WORKERS: 0
AUG_MULTIPLIER: 5  # on-the-fly: effectively 5x train set

MEAN: [0.485, 0.456, 0.406]
STD: [0.229, 0.224, 0.225]

EPOCHS: 5
OPTIMIZER: "adamw"
LR: 0.001
LR_ENCODER: 0.0001
LR_HEAD: 0.001
WEIGHT_DECAY: 0.0001
SCHEDULER: "plateau"
EARLY_STOPPING_PATIENCE: 8
GRAD_CLIP_NORM: 1.0
AMP: false

MODEL_NAME: "scratch_ed"    # scratch_ed | scratch_ed_plus | unet_mini | unet_mini_dropout | segformer_lite
BASE_CHANNELS: 32
ASPP_RATES: [1, 6, 12, 18]
DROPOUT: 0.3
ENCODER: "segformer_b0"
PRETRAINED: 1
FREEZE_EPOCHS: 5

LOSS: "bce_dice"
THRESHOLD: 0.19
